# Generated by Django 3.1.2 on 2020-12-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201116_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='good_count',
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triviaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_relationships', to='api.trivia')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trivia',
            name='good',
            field=models.ManyToManyField(through='api.Good', to=settings.AUTH_USER_MODEL, verbose_name='好ユーザリスト'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.UniqueConstraint(fields=('userId', 'triviaId'), name='unique_set'),
        ),
    ]
