# Generated by Django 3.1.2 on 2020-12-15 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201215_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='good',
            field=models.ManyToManyField(through='api.Good', to=settings.AUTH_USER_MODEL, verbose_name='好ユーザリスト'),
        ),
    ]
