# Generated by Django 3.1.2 on 2020-12-15 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201215_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='good',
            field=models.ManyToManyField(through='api.Good', to=settings.AUTH_USER_MODEL),
        ),
    ]
